### ISSUE TITLE
[Feature] Add a small indicator in the member's list to know who is the owner of the guild

### ISSUE THREAD

**Issue by theoludwig** [Thream/website#19]
## Description

Currently, we don't know who owns the guild, it might be nice to add a small indicator in the member's list to see who is the owner.

This indicator could be for example a little crown 👑 near the nickname of the user or the picture, feel free to suggest other ideas.

![image](https://user-images.githubusercontent.com/25207499/161121538-e6834e56-475a-4134-ace2-6a577c364415.png)

**Comment by ritikBhandari** [comment]
Hi,
Can I work on this issue?

**Comment by theoludwig** [comment]
Hey! @ritikBhandari :wave:

Sure, you can, thanks for your interest and proposal!
We plan to release the first public version of Thream soon: 09/04/2022. :smile:

To get started, you can start to clone the API first https://github.com/Thream/api and follow the instructions for a development setup, the easiest would be to use a dev container with VSCode and Docker.
And then of course to clone this repository and follow the instructions here (much simpler), simply do `npm install` and `npm run dev`.
Also, you might want to take a look at https://github.com/Thream/website/blob/develop/CONTRIBUTING.md.

If you have issues with the setup, feel free to ask questions here, will be happy to help. :smile:

**Comment by ritikBhandari** [comment]
Sure. Thank you
