### ISSUE TITLE
[Feature] Edit/Delete a Message

### ISSUE THREAD

**Issue by theoludwig** [Thream/website#20]
## Description

To edit or delete a message, we must use the API, it would be great to use a "trash" button :wastebasket: to delete or a "pen" :pen: button to edit a message with the UI (User Interface).

![image](https://user-images.githubusercontent.com/25207499/161122728-13a8a0b9-9afb-4eae-b8d5-fc4464675a1b.png)

**Comment by walidkorchi** [comment]
@Divlo, Is it necessary to ask the user if he's really sure that he wants to delete messages in a confirmation popup? Except of course for changing messages, it would annoying to ask every single time. 👀

**Comment by theoludwig** [comment]
@Walidoux No, not necessarily, feel free to implement this feature as you want.
