### ISSUE TITLE
[Feature] Confirm Popup for Guild/Channel deletion

### ISSUE THREAD

**Issue by theoludwig** [Thream/website#23]
## Description

Similar to joining a guild, we could have a popup warning the user that we can't go back after a channel or a guild deletion and that the user must be sure that it is what the user wants to do.

![image](https://user-images.githubusercontent.com/25207499/161126721-185afed4-0fe0-439f-ad9c-e582de39d116.png)

![image](https://user-images.githubusercontent.com/25207499/161126882-3731017e-0b27-4289-bb91-ce883091e987.png)

**Comment by walidkorchi** [comment]
I'll make sure it will be done for the next two days.
