### ISSUE TITLE
[Bug] Bad render for apple devices including responsiveness

### ISSUE THREAD

**Issue by walidkorchi** [Thream/website#28]
## 🐛 What are the bugs?

1. Icons aren't visible on iPhone such as (the Hamburger menu / Guild Settings / Channel creation)
2. For responsiveness:
- The list of public guilds has an extra margin or padding.
- The profile page doesn't even have responsive or not detecting media queries.

## 📷 Screenshots:
![IMG_3446](https://user-images.githubusercontent.com/87608619/162621256-74c31f71-c373-47fb-9f9c-c0312e9e627f.png)
![IMG_3447](https://user-images.githubusercontent.com/87608619/162621259-fef01d0d-6640-421d-96fa-96c9178b5256.png)
![IMG_3448](https://user-images.githubusercontent.com/87608619/162621261-84db83e3-d2e9-4e9d-b43a-fbb13590f517.png)

**Comment by theoludwig** [comment]
Closing as Thream now enters Maintenance mode (only critical bug issues will be considered, no features planned in the future), we might take Thream down and archive the repositories (`website`, `api` `file-uploads-api, not npm packages) on GitHub in the coming year.
